routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    $last=DB::connection('mysql')->select('select f.*,t.name as type_name from food_details f
left join food_type t ON f.food_type = t.id
ORDER BY id DESC LIMIT 1');
//    dd($last[0]);
    $sale=DB::connection('mysql')->select('select * from v_sale');
//    dd($sale);
    $popu= DB::connection('mysql')->select('SELECT s.food_id ,f.name AS food_name,
  f.image,f.price,f.food_type,t.name AS type_name
  ,COUNT(*) AS magnitude
FROM food_rated s
  LEFT JOIN food_details f on s.food_id = f.id
  LEFT JOIN food_type t ON f.food_type = t.id
GROUP BY food_id
ORDER BY magnitude DESC
LIMIT 1');
    return view('welcome',['last'=>$last,'sale'=>$sale,'popu'=>$popu]);
//    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/details','FoodDetailsController');
Route::resource('/search','SearchController');

app/FoodDetails.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FoodDetails extends Model
{
    protected $table = 'food_details';
    protected $fillable = ['name', 'price','cal','image','food_type'];

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FoodDetailsController.php
<?php

namespace App\Http\Controllers;

use App\FoodDetails;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class FoodDetailsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function fileUpload($document)
    {
        try{
            $input['document'] = time().'_'.$document->getClientOriginalName();

            $destinationPath = public_path('/document');

            $document->move($destinationPath, $input['document']);


            //$this->postImage->add($input);

            return $input['document'];
        }
        catch(Exception $ex)
        {
            return false;
        }
    }

    public function index()
    {
        $food_type=DB::table('food_type')->get();
        return view('food.create',['food_type'=>$food_type]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        dd(Auth::user());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        dd($request);
        $this->validate($request,[
            'name'=>'required',
            'price'=>'required',
            'cal'=>'required',
            'food_type'=>'required',
        ],[
            'name.required'=>' Name is required.',
            'price.required'=>'price is required',
            'cal.required'=>'cal is required.',
            'food_type.required'=>'Type is required',
//            'logo.required'=>'logo is required.',
        ]);
        if ($request->document != null) {

            $documents = $request->file('document');
            $document = $this->fileUpload($documents);
            $request['image'] = $document;

//            dd($request->input());

        }
//        $image = $request->file('logo');
        if(FoodDetails::create($request->input())){
//            $request['logo'] = $image_name;
//            $company = Company::create($request->input());
            return redirect()
                ->action('FoodDetailsController@index')
                ->with(['success'=>"Items Created Successfully."]);
        }else{
            return redirect()
                ->action('FoodDetailsController@index')
                ->with(['Failed'=>"Company Created Failed."]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class SearchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('search.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        dd($request->input());
        $result=DB::select('select f.*,t.name as type_name from food_details f
left join food_type t ON f.food_type = t.id
WHERE f.food_type = '.$request->input('food_type').' and f.price < '.$request->input('price').'
 and f.cal < '.$request->input('cal').'
');
//        dd($result);
        return view('search.index',['result'=>$result]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/food/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 10-05-2019
 * Time: 1:04 PM
 */?>
@extends('layouts.layout')
@section('content')
    <br>
    <div class="row">
        <div class="col-md-12 profile-dashboard">
            <div class="row">
                <div class="col-md-7 dashboard-form calender">
                    <form class="form-horizontal" action="{{route('details.store')}}" enctype="multipart/form-data" method="post">
                        {{csrf_field()}}
                        <div class="bg-white pinside40 mb30">
                            <!-- Form Name -->
                            <h2 class="form-title">Upload Photo</h2>
                            <div class="form-group">
                                {{--<div class="col-md-4">--}}
                                    {{--<div class="photo-upload"><img src="images/profile-dashbaord.png" alt=""></div>--}}
                                {{--</div>--}}
                                <div class="col-md-8 upload-file">
                                    <input  name="document" class="input-file" type="file" value="">
                                </div>
                            </div>
                            <!-- Text input-->
                            <h2 class="form-title">Food Details</h2>
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="name">Name<span class="required">*</span></label>
                                <div class="col-md-8">
                                    <input id="name" name="name" type="text" placeholder="Name" class="form-control input-md" required="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="name">Price </label>
                                <div class="col-md-8">
                                    <input id="name" name="price" type="number" step="any" placeholder="Price" class="form-control input-md" required="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="name">Food Type<span class="required">*</span></label>
                                <div class="col-md-8">
                                    <select id="name" name="food_type" type="text" class="form-control input-md" required="">
                                        <option value="" selected disabled>Select Type</option>
                                        @foreach($food_type as $food)
                                            <option value="{{$food->id}}">{{$food->name}}</option>
                                            @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="name">Cal<span class="required">*</span></label>
                                <div class="col-md-8">
                                    <input id="name" name="cal" type="number" step="any" placeholder="Cal" class="form-control input-md" required="">
                                </div>
                            </div>

                            <!-- Button -->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="submit"></label>
                                <div class="col-md-4">
                                    <button id="submit" name="submit" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {{--</div>--}}
    @endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/layout.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 10-05-2019
 * Time: 9:40 AM
 */?>

        <!DOCTYPE html>
<html  lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Osteria Food Market</title>
    <!-- Bootstrap -->
    <link href="{{asset('assets/css/bootstrap.min.css')}}" rel="stylesheet">
    <!-- Template style.css -->
    <link rel="stylesheet" type="text/css" href="{{asset('assets/css/style.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assets/css/owl.carousel.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assets/css/owl.theme.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assets/css/owl.transitions.css')}}">
    <!-- Font used in template -->
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700|Roboto:400,400italic,500,500italic,700,700italic,300italic,300' rel='stylesheet' type='text/css'>
    <!--font awesome icon -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- favicon icon -->
    <link rel="shortcut icon" href="{{asset('assets/images/logo2.png')}}" type="image/x-icon">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<div class="collapse" id="searcharea">
    <!-- top search -->
    <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for...">
        <span class="input-group-btn">
              <button class="btn btn-primary" type="button">Search</button>
          </span>
    </div>
</div>
<!-- /.top search -->
{{--<div class="top-bar">--}}
    {{--<div class="container">--}}
        {{--<div class="row">--}}
            {{--<div class="col-md-6 top-message">--}}
                {{--<p>Welcome to Osteria Food.</p>--}}
            {{--</div>--}}
            {{--<div class="col-md-6 top-links">--}}
                {{--<ul class="listnone">--}}
                    {{--@if (Route::has('login'))--}}
                        {{--<li >--}}
                            {{--@auth--}}
                                {{--<a href="{{Auth::logout()}}">Logout</a>--}}
                                {{--<a href="{{route('details.index')}}">Details</a>--}}
                                {{--@else--}}
                                    {{--<li>--}}
                                    {{--<a href="{{ route('login') }}">Login</a>--}}
                                    {{--</li>--}}
                                    {{--@if (Route::has('register'))--}}
                                        {{--<li>--}}
                                        {{--<a href="{{ route('register') }}">Register</a>--}}
                                        {{--</li>--}}
                                            {{--@endif--}}
                                    {{--@endauth--}}
                        {{--</li>--}}
                    {{--@endif--}}
                    {{--<li><a href="login-page.html">Log in</a></li>--}}
                    {{--<li>--}}
                        {{--<a role="button" data-toggle="collapse" href="#searcharea" aria-expanded="false" aria-controls="searcharea"> <i class="fa fa-search"></i> </a>--}}
                    {{--</li>--}}
                {{--</ul>--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</div>--}}
{{--</div>--}}
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-12 logo">
                <div class="navbar-brand">
                    <a href="{{ url('/') }}"><img src="{{asset('assets/images/logo2.png')}}" alt="Wedding Vendors" class="img-responsive"></a>
                </div>
            </div>
            <div class="col-md-9 col-sm-12">
                <div class="navigation" id="navigation">
                    <ul>
                        <li class="active"><a href="{{ url('/') }}">Home</a>
                        </li>
                        @if (Route::has('login'))
                            <li >
                                @auth
                                <li>
                                    <a href="{{route('details.index')}}">Details</a>
                                </li>
                                    <li>
                                    <a href="{{Auth::logout()}}">Logout</a>
                                    </li>

                            <li>

                            </li>
                        @else
                            <li>
                                <a href="{{ route('login') }}">Login</a>
                            </li>
                            @if (Route::has('register'))
                                <li>
                                    <a href="{{ route('register') }}">Register</a>
                                </li>
                                @endif
                                @endauth
                                </li>
                            @endif


                        </li>

                            </ul>

                </div>

            </div>
        </div>
    </div>
</div>
@yield('content')
<div class="footer">
    <!-- Footer -->
    <div class="container">
        <div class="row">
            <div class="col-md-5 ft-aboutus">
                <h2>Osteria Food</h2>
                <p>At Osteria food Market you find what with delicious food . <a href="#">Start Find Food!</a></p>
                <a href="#" class="btn btn-default">Find a Food</a> </div>
            <div class="col-md-3 ft-link">
                <h2>Useful links</h2>
                <ul>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Contact us</a></li>
                    <li><a href="#">News</a></li>
                    <li><a href="#">Career</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Terms of Use</a></li>
                </ul>
            </div>
            <div class="col-md-4 newsletter">
                <h2>Subscribe for Newsletter</h2>
                <form>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Enter E-Mail Address" required>
                        <span class="input-group-btn">
            <button class="btn btn-default" type="button">Submit</button>
            </span> </div>
                    <!-- /input-group -->
                    <!-- /.col-lg-6 -->
                </form>
                <div class="social-icon">
                    <h2>Be Social &amp; Stay Connected</h2>
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus-square"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-flickr"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.Footer -->
<div class="tiny-footer">
    <!-- Tiny footer -->
    <div class="container">
        <div class="row">
            <div class="col-md-12">Copyright © 2019. All Rights Reserved</div>
        </div>
    </div>
</div>

<script src="{{asset('assets/js/jquery.min.js')}}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{{asset('assets/js/bootstrap.min.js')}}"></script>
<!-- Flex Nav Script -->
<script src="{{asset('assets/js/jquery.flexnav.js')}}" type="text/javascript"></script>
<script src="{{asset('assets/js/navigation.js')}}"></script>
<!-- slider -->
<script src="{{asset('assets/js/owl.carousel.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/js/slider.js')}}"></script>
<!-- testimonial -->
<script type="text/javascript" src="{{asset('assets/js/testimonial.js')}}"></script>
<!-- sticky header -->
<script src="{{asset('assets/js/jquery.sticky.js')}}"></script>
<script src="{{asset('assets/js/header-sticky.js')}}"></script>
</body>

</html>